name: CI

on: push

jobs:
  lint:
    uses: jill64/workflows/.github/workflows/lint.yml@main
  check:
    uses: jill64/workflows/.github/workflows/check.yml@main
  publish-pages:
    uses: jill64/workflows/.github/workflows/publish-pages.yml@main
